"""Deterministic PyBullet runner for the differential-drive project adapter.

This module deliberately writes a durable run directory.  Agent-facing tools
can return its compact summary while numerical and visual evidence stays local
and can be requested by path/time later.

The generated controller ABI is intentionally small::

    def compute_wheel_commands(observation: dict) -> dict[str, float]:
        return {"left_wheel_rad_s": 8.0, "right_wheel_rad_s": 8.0}

``observation["oracle"]`` is explicitly simulator/evaluation data.  A future
ROS adapter can provide the same robot-facing fields without that key.
"""

from __future__ import annotations

import argparse
import contextlib
import hashlib
import importlib.util
import io
import json
import math
import sys
import time
import traceback
import uuid
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Callable, Mapping

import numpy as np
from PIL import Image

from .morphology import DEFAULT_SPEC, normalize_spec, write_morphology


SIM_DT = 1.0 / 240.0
SAMPLE_HZ = 20.0
FRAME_WIDTH = 320
FRAME_HEIGHT = 240
SUCCESS_DISTANCE_M = 0.30
TARGET_XY = (1.8, 0.0)
ADAPTER_FAMILIES = {
    "rail_train_kinematic",
    "articulated_position_control",
}

DEFAULT_CONTROLLER = '''"""Baseline rover controller generated by RoboPilot.

The target coordinates are marked oracle/evaluation because they come from the
simulator. Replace this with perception-driven logic when adding real sensors.
"""
import json
import math
from pathlib import Path


def _mission() -> dict:
    path = Path(__file__).with_name("mission.json")
    try:
        value = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return {"mode": "target_seek", "parameters": {}}
    return value if isinstance(value, dict) else {"mode": "target_seek", "parameters": {}}


def compute_wheel_commands(observation: dict) -> dict[str, float]:
    mission = _mission()
    parameters = mission.get("parameters", {})
    parameters = parameters if isinstance(parameters, dict) else {}
    mode = mission.get("mode", "target_seek")
    if mode == "wheel_velocity":
        return {
            "left_wheel_rad_s": float(parameters.get("left_wheel_rad_s", 0.0)),
            "right_wheel_rad_s": float(parameters.get("right_wheel_rad_s", 0.0)),
        }
    if mode == "circle":
        speed = float(parameters.get("speed_rad_s", 6.0))
        turn = abs(float(parameters.get("turn_rad_s", 2.0)))
        direction = -1.0 if parameters.get("direction") == "clockwise" else 1.0
        return {"left_wheel_rad_s": speed - direction * turn, "right_wheel_rad_s": speed + direction * turn}
    x, y, _ = observation["odometry"]["position_xyz"]
    yaw = observation["odometry"]["yaw_rad"]
    target_x, target_y = observation["oracle"]["target_xy"]
    heading = math.atan2(target_y - y, target_x - x)
    error = (heading - yaw + math.pi) % (2 * math.pi) - math.pi
    distance = math.hypot(target_x - x, target_y - y)
    if distance < 0.14:
        return {"left_wheel_rad_s": 0.0, "right_wheel_rad_s": 0.0}
    forward = min(float(parameters.get("max_speed_rad_s", 7.0)), 3.0 + distance * 2.0)
    turn = max(-4.5, min(4.5, float(parameters.get("turn_gain", 5.0)) * error))
    return {"left_wheel_rad_s": forward - turn, "right_wheel_rad_s": forward + turn}
'''


@dataclass(frozen=True)
class Controller:
    compute: Callable[[dict[str, Any]], Mapping[str, Any] | tuple[Any, Any] | list[Any]]
    path: Path


def create_demo_project(workspace: str | Path, *, overwrite: bool = False) -> Path:
    """Create the hand-written golden-path project and return its directory."""

    directory = Path(workspace).resolve()
    write_morphology(directory, DEFAULT_SPEC)
    controller_path = directory / "controller.py"
    if overwrite or not controller_path.exists():
        controller_path.write_text(DEFAULT_CONTROLLER, encoding="utf-8")
    return directory


def _require_pybullet() -> tuple[Any, Any]:
    try:
        import pybullet as bullet
        import pybullet_data
    except ImportError as exc:  # pragma: no cover - depends on environment setup
        raise RuntimeError("PyBullet is required: install requirements.txt") from exc
    return bullet, pybullet_data


def _load_spec(workspace: Path) -> dict[str, Any]:
    spec_path = workspace / "spec.json"
    if not spec_path.exists():
        return normalize_spec(DEFAULT_SPEC)
    try:
        raw = json.loads(spec_path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        raise ValueError(f"cannot read {spec_path.name}: {exc}") from exc
    return normalize_spec(raw)


def _project_morphology(workspace: Path) -> str:
    """Read the declared robot class before applying the rover-only schema."""
    try:
        raw = json.loads((workspace / "spec.json").read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return "differential_drive"
    morphology = raw.get("morphology") if isinstance(raw, Mapping) else None
    kind = morphology.get("type") if isinstance(morphology, Mapping) else morphology
    return kind if isinstance(kind, str) else "unknown"


def _project_adapter_family(workspace: Path, morphology: str, *, allow_draft: bool = False) -> str | None:
    """Return a validated project-local adapter family, never arbitrary code.

    Adapter declarations are deliberately data-only.  They let an agent map a
    newly named robot type onto an existing, bounded simulator family without
    granting it write access to the RoboPilot server or a way to register
    arbitrary Python as a global plugin.
    """
    try:
        raw = json.loads((workspace / "adapter.json").read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return None
    if not isinstance(raw, Mapping):
        return None
    if raw.get("morphology") != morphology:
        return None
    status = raw.get("status")
    if status != "validated" and not (allow_draft and status == "draft"):
        return None
    family = raw.get("family")
    return family if family in ADAPTER_FAMILIES else None


def _artifact_revision(workspace: Path) -> str:
    digest = hashlib.sha256()
    for name in ("spec.json", "adapter.json", "robot.urdf", "controller.py", "train_controller.py", "mission.json"):
        path = workspace / name
        digest.update(name.encode("utf-8"))
        if path.exists():
            digest.update(path.read_bytes())
    return f"rev_{digest.hexdigest()[:12]}"


def _load_controller(path: Path) -> Controller:
    if not path.exists():
        raise FileNotFoundError(f"controller not found: {path}")
    module_name = f"robopilot_controller_{uuid.uuid4().hex}"
    module_spec = importlib.util.spec_from_file_location(module_name, path)
    if module_spec is None or module_spec.loader is None:
        raise RuntimeError(f"cannot load controller: {path}")
    module = importlib.util.module_from_spec(module_spec)
    module_spec.loader.exec_module(module)
    compute = getattr(module, "compute_wheel_commands", None)
    if not callable(compute):
        raise TypeError("controller must define compute_wheel_commands(observation)")
    return Controller(compute=compute, path=path)


def _commands(result: Any) -> tuple[float, float]:
    if isinstance(result, Mapping):
        left = result.get("left_wheel_rad_s", result.get("left"))
        right = result.get("right_wheel_rad_s", result.get("right"))
    elif isinstance(result, (tuple, list)) and len(result) == 2:
        left, right = result
    else:
        raise TypeError("controller result must be wheel mapping or [left, right]")
    left, right = float(left), float(right)
    if not (math.isfinite(left) and math.isfinite(right)):
        raise ValueError("wheel commands must be finite")
    # A bad agent edit must not destabilise the physics loop indefinitely.
    return max(-40.0, min(40.0, left)), max(-40.0, min(40.0, right))


def _yaw(quaternion: list[float] | tuple[float, ...], bullet: Any) -> float:
    return float(bullet.getEulerFromQuaternion(quaternion)[2])


def _camera_frame(bullet: Any, robot_id: int, frame_path: Path) -> None:
    position, quaternion = bullet.getBasePositionAndOrientation(robot_id)
    yaw = _yaw(quaternion, bullet)
    forward = np.array([math.cos(yaw), math.sin(yaw), 0.0])
    eye = np.array(position, dtype=float) + forward * 0.14 + np.array([0.0, 0.0, 0.11])
    target = eye + forward * 3.0
    view = bullet.computeViewMatrix(eye.tolist(), target.tolist(), [0.0, 0.0, 1.0])
    projection = bullet.computeProjectionMatrixFOV(fov=72, aspect=FRAME_WIDTH / FRAME_HEIGHT, nearVal=0.03, farVal=8.0)
    _, _, rgba, _, _ = bullet.getCameraImage(
        FRAME_WIDTH,
        FRAME_HEIGHT,
        viewMatrix=view,
        projectionMatrix=projection,
        renderer=bullet.ER_TINY_RENDERER,
    )
    pixels = np.asarray(rgba, dtype=np.uint8).reshape((FRAME_HEIGHT, FRAME_WIDTH, 4))
    Image.fromarray(pixels[:, :, :3], mode="RGB").save(frame_path, format="JPEG", quality=88)


def _observation(
    sim_time_s: float,
    position: tuple[float, float, float],
    yaw_rad: float,
    wheel_positions: tuple[float, float],
    wheel_velocities: tuple[float, float],
) -> dict[str, Any]:
    return {
        "t": round(sim_time_s, 6),
        "odometry": {"position_xyz": list(position), "yaw_rad": yaw_rad, "frame_id": "world"},
        "joint_state": {
            "names": ["left_wheel_joint", "right_wheel_joint"],
            "position_rad": list(wheel_positions),
            "velocity_rad_s": list(wheel_velocities),
        },
        "oracle": {
            "source": "simulator/evaluation",
            "target_xy": list(TARGET_XY),
            "note": "Not a physical robot sensor; do not rely on this for hardware controllers.",
        },
    }


def _write_jsonl(path: Path, rows: list[dict[str, Any]]) -> None:
    with path.open("w", encoding="utf-8") as handle:
        for row in rows:
            handle.write(json.dumps(row, separators=(",", ":")) + "\n")


def run_simulation(
    workspace: str | Path,
    *,
    duration_s: float = 10.0,
    mode: str = "batch",
    scenario: str = "default",
    run_id: str | None = None,
    artifact_revision: str | None = None,
    on_state: Callable[[dict[str, Any], dict[str, Any]], None] | None = None,
    allow_draft_adapter: bool = False,
) -> dict[str, Any]:
    """Run a project controller and write a canonical, session-local run record.

    ``mode="live"`` uses identical deterministic physics but throttles each step
    to real time. Streaming is intentionally owned by the platform layer; it
    can replay the returned ``state_samples_path`` for batch runs or relay
    samples while this callable is executed on a worker for live runs.
    """

    if not 0.1 <= float(duration_s) <= 120.0:
        raise ValueError("duration_s must be in [0.1, 120]")
    if mode not in {"batch", "live"}:
        raise ValueError("mode must be 'batch' or 'live'")
    if not scenario or len(scenario) > 80:
        raise ValueError("scenario must be a non-empty string up to 80 characters")

    workspace_path = Path(workspace).resolve()
    workspace_path.mkdir(parents=True, exist_ok=True)
    morphology_kind = _project_morphology(workspace_path)
    adapter_family = _project_adapter_family(
        workspace_path, morphology_kind, allow_draft=allow_draft_adapter
    )
    if morphology_kind == "rail_train" or adapter_family == "rail_train_kinematic":
        return run_rail_train_simulation(
            workspace_path,
            duration_s=duration_s,
            mode=mode,
            scenario=scenario,
            run_id=run_id,
            artifact_revision=artifact_revision,
            on_state=on_state,
        )
    if morphology_kind != "differential_drive":
        return run_articulated_simulation(
            workspace_path,
            morphology=morphology_kind,
            duration_s=duration_s,
            mode=mode,
            scenario=scenario,
            run_id=run_id,
            artifact_revision=artifact_revision,
            on_state=on_state,
            allow_declared_morphology=adapter_family == "articulated_position_control",
        )
    spec = _load_spec(workspace_path)
    urdf_path = workspace_path / "robot.urdf"
    if not urdf_path.exists():
        write_morphology(workspace_path, spec)
    controller_path = workspace_path / "controller.py"
    if not controller_path.exists():
        controller_path.write_text(DEFAULT_CONTROLLER, encoding="utf-8")

    actual_run_id = run_id or f"run_{uuid.uuid4().hex[:12]}"
    if not actual_run_id.replace("_", "").replace("-", "").isalnum():
        raise ValueError("run_id may contain only letters, digits, '_' and '-'")
    run_dir = workspace_path / "runs" / actual_run_id
    if run_dir.exists():
        raise FileExistsError(f"run already exists: {actual_run_id}")
    frames_dir = run_dir / "frames"
    frames_dir.mkdir(parents=True)

    revision = artifact_revision or _artifact_revision(workspace_path)
    signals: list[dict[str, Any]] = []
    states: list[dict[str, Any]] = []
    frames: list[dict[str, Any]] = []
    controller_output = io.StringIO()
    stderr = ""
    status = "task_failed"
    bullet, pybullet_data = _require_pybullet()
    client_id = bullet.connect(bullet.DIRECT)
    started = time.monotonic()

    try:
        bullet.resetSimulation(physicsClientId=client_id)
        bullet.setAdditionalSearchPath(pybullet_data.getDataPath(), physicsClientId=client_id)
        bullet.setGravity(0, 0, -9.81, physicsClientId=client_id)
        bullet.setTimeStep(SIM_DT, physicsClientId=client_id)
        bullet.loadURDF("plane.urdf", physicsClientId=client_id)

        morphology = spec["morphology"]
        initial_z = morphology["wheel_radius_m"] + morphology["body_height_m"] / 2.0 + 0.002
        robot_id = bullet.loadURDF(
            str(urdf_path), [0.0, 0.0, initial_z], useFixedBase=False, flags=bullet.URDF_USE_INERTIA_FROM_FILE,
            physicsClientId=client_id,
        )
        bullet.changeDynamics(robot_id, -1, lateralFriction=0.9, physicsClientId=client_id)
        for joint_index in range(bullet.getNumJoints(robot_id, physicsClientId=client_id)):
            bullet.changeDynamics(robot_id, joint_index, lateralFriction=1.4, physicsClientId=client_id)

        target_id = bullet.createMultiBody(
            baseMass=0.0,
            baseVisualShapeIndex=bullet.createVisualShape(
                bullet.GEOM_SPHERE, radius=0.10, rgbaColor=[0.92, 0.05, 0.04, 1.0], physicsClientId=client_id
            ),
            basePosition=[TARGET_XY[0], TARGET_XY[1], 0.10],
            physicsClientId=client_id,
        )
        bullet.setCollisionFilterGroupMask(target_id, -1, 0, 0, physicsClientId=client_id)

        joint_indices = {
            bullet.getJointInfo(robot_id, index, physicsClientId=client_id)[1].decode("utf-8"): index
            for index in range(bullet.getNumJoints(robot_id, physicsClientId=client_id))
        }
        try:
            left_joint = joint_indices["left_wheel_joint"]
            right_joint = joint_indices["right_wheel_joint"]
        except KeyError as exc:
            raise RuntimeError("URDF must expose left_wheel_joint and right_wheel_joint") from exc
        bullet.setJointMotorControlArray(
            robot_id, [left_joint, right_joint], bullet.VELOCITY_CONTROL, targetVelocities=[0, 0], forces=[2.5, 2.5],
            physicsClientId=client_id,
        )
        controller = _load_controller(controller_path)

        total_steps = max(1, int(round(float(duration_s) / SIM_DT)))
        sample_every = max(1, int(round((1.0 / SAMPLE_HZ) / SIM_DT)))
        frame_steps = {0, total_steps // 2, total_steps - 1}
        yaw_initial: float | None = None
        last_commands = (0.0, 0.0)

        for step in range(total_steps):
            sim_time_s = step * SIM_DT
            position_raw, quat_raw = bullet.getBasePositionAndOrientation(robot_id, physicsClientId=client_id)
            joint_states = bullet.getJointStates(robot_id, [left_joint, right_joint], physicsClientId=client_id)
            wheel_positions = (float(joint_states[0][0]), float(joint_states[1][0]))
            wheel_velocities = (float(joint_states[0][1]), float(joint_states[1][1]))
            yaw_rad = _yaw(quat_raw, bullet)
            if yaw_initial is None:
                yaw_initial = yaw_rad
            observation = _observation(sim_time_s, tuple(position_raw), yaw_rad, wheel_positions, wheel_velocities)
            try:
                with contextlib.redirect_stdout(controller_output):
                    last_commands = _commands(controller.compute(observation))
            except Exception:
                status = "crashed"
                stderr = traceback.format_exc(limit=8)
                break
            bullet.setJointMotorControlArray(
                robot_id,
                [left_joint, right_joint],
                bullet.VELOCITY_CONTROL,
                targetVelocities=list(last_commands),
                forces=[2.5, 2.5],
                physicsClientId=client_id,
            )
            bullet.stepSimulation(physicsClientId=client_id)

            if step % sample_every == 0 or step == total_steps - 1:
                position_raw, quat_raw = bullet.getBasePositionAndOrientation(robot_id, physicsClientId=client_id)
                joint_states = bullet.getJointStates(robot_id, [left_joint, right_joint], physicsClientId=client_id)
                yaw_rad = _yaw(quat_raw, bullet)
                distance = math.hypot(position_raw[0] - TARGET_XY[0], position_raw[1] - TARGET_XY[1])
                roll, pitch, _ = bullet.getEulerFromQuaternion(quat_raw)
                sample = {
                    "t": round((step + 1) * SIM_DT, 6),
                    "base_pos": [float(value) for value in position_raw],
                    "base_quat": [float(value) for value in quat_raw],
                    "joints": {"left_wheel": float(joint_states[0][0]), "right_wheel": float(joint_states[1][0])},
                }
                signal = {
                    "t": sample["t"],
                    "base_x_m": sample["base_pos"][0],
                    "base_y_m": sample["base_pos"][1],
                    "yaw_rad": yaw_rad,
                    "dist_to_target_m": distance,
                    "left_command_rad_s": last_commands[0],
                    "right_command_rad_s": last_commands[1],
                    "left_wheel_velocity_rad_s": float(joint_states[0][1]),
                    "right_wheel_velocity_rad_s": float(joint_states[1][1]),
                    "roll_rad": float(roll),
                    "pitch_rad": float(pitch),
                }
                states.append(sample)
                signals.append(signal)
                if on_state is not None:
                    on_state(sample, signal)
            if step in frame_steps:
                frame_path = frames_dir / f"robot_rgb_{step:06d}.jpg"
                _camera_frame(bullet, robot_id, frame_path)
                frames.append({"camera": "robot_rgb", "t": round((step + 1) * SIM_DT, 6), "path": str(frame_path)})
            if mode == "live":
                target_wall = started + (step + 1) * SIM_DT
                time.sleep(max(0.0, target_wall - time.monotonic()))

        if not signals:
            raise RuntimeError("simulation did not produce any state samples")
        final = signals[-1]
        final_state = states[-1]
        if status != "crashed":
            status = "task_success" if final["dist_to_target_m"] < SUCCESS_DISTANCE_M else "task_failed"
        yaw_start = signals[0]["yaw_rad"]
        yaw_end = final["yaw_rad"]
        # Keep yaw drift intuitive across +/- pi.
        yaw_drift = math.degrees((yaw_end - yaw_start + math.pi) % (2 * math.pi) - math.pi)
        max_tilt = max(math.degrees(max(abs(row["roll_rad"]), abs(row["pitch_rad"]))) for row in signals)
        collisions = 0  # Ground contacts and target proximity are not task collisions.
        summary = {
            "final_base_pose": {
                "xyz": final_state["base_pos"],
                "rpy": [final["roll_rad"], final["pitch_rad"], final["yaw_rad"]],
            },
            "distance_to_target_m": final["dist_to_target_m"],
            "total_yaw_drift_deg": yaw_drift,
            "mean_wheel_velocities": {
                "left": float(np.mean([row["left_wheel_velocity_rad_s"] for row in signals])),
                "right": float(np.mean([row["right_wheel_velocity_rad_s"] for row in signals])),
            },
            "collisions": collisions,
            "max_tilt_deg": max_tilt,
            "sim_time_s": final["t"],
        }
    except Exception:
        if not stderr:
            status = "crashed"
            stderr = traceback.format_exc(limit=12)
        summary = {
            "final_base_pose": {"xyz": [0.0, 0.0, 0.0], "rpy": [0.0, 0.0, 0.0]},
            "distance_to_target_m": None,
            "total_yaw_drift_deg": 0.0,
            "mean_wheel_velocities": {"left": 0.0, "right": 0.0},
            "collisions": 0,
            "max_tilt_deg": 0.0,
            "sim_time_s": 0.0,
        }
    finally:
        if client_id >= 0:
            bullet.disconnect(physicsClientId=client_id)

    stderr = stderr[:2000]
    controller_log_path = run_dir / "controller.log"
    controller_log_path.write_text(controller_output.getvalue()[-10_000:], encoding="utf-8")
    signals_path = run_dir / "signals.jsonl"
    states_path = run_dir / "states.jsonl"
    _write_jsonl(signals_path, signals)
    _write_jsonl(states_path, states)
    record = {
        "schema_version": "0.1.0",
        "run_id": actual_run_id,
        "artifact_revision": revision,
        "status": status,
        "stderr": stderr,
        "telemetry_summary": summary,
        "evidence": {"frames": frames, "signals_path": str(signals_path)},
        "state_samples_path": str(states_path),
        "controller_log_path": str(controller_log_path),
        "mode": mode,
        "scenario": scenario,
        "oracle": {"target_xy": list(TARGET_XY), "source": "simulator/evaluation"},
    }
    record_path = run_dir / "run_record.json"
    record_path.write_text(json.dumps(record, indent=2) + "\n", encoding="utf-8")
    record["record_path"] = str(record_path)
    return record


def _articulated_targets(controller_path: Path, joint_names: list[str], positions: dict[str, float]) -> dict[str, float]:
    """Support a small, explicit joint-target ABI plus the bundled hand controller."""
    module_name = f"robopilot_articulated_{uuid.uuid4().hex}"
    module_spec = importlib.util.spec_from_file_location(module_name, controller_path)
    if module_spec is None or module_spec.loader is None:
        return positions
    module = importlib.util.module_from_spec(module_spec)
    module_spec.loader.exec_module(module)
    compute = getattr(module, "compute_joint_targets", None)
    if callable(compute):
        value = compute({"joint_position": positions, "joint_names": joint_names})
        if isinstance(value, Mapping):
            return {name: float(value[name]) for name in joint_names if name in value}
    targets = getattr(module, "JOINT_TARGETS", None)
    if isinstance(targets, Mapping):
        return {name: float(targets[name]) for name in joint_names if name in targets}
    hand_type = getattr(module, "HandController", None)
    if hand_type is not None:
        hand = hand_type()
        close_pose = getattr(hand, "close_pose", None)
        if callable(close_pose):
            hand.set_target(close_pose())
            ordered = getattr(module, "JOINTS", ())
            return {name: float(value) for name, value in zip(ordered, hand.command()) if name in joint_names}
    return positions


def _articulated_camera(bullet: Any, robot_id: int, frame_path: Path) -> None:
    position, _ = bullet.getBasePositionAndOrientation(robot_id)
    eye = [position[0] + 0.65, position[1] - 0.65, position[2] + 0.5]
    view = bullet.computeViewMatrix(eye, [position[0], position[1], position[2] + 0.2], [0.0, 0.0, 1.0])
    projection = bullet.computeProjectionMatrixFOV(fov=58, aspect=FRAME_WIDTH / FRAME_HEIGHT, nearVal=0.03, farVal=5.0)
    _, _, rgba, _, _ = bullet.getCameraImage(FRAME_WIDTH, FRAME_HEIGHT, viewMatrix=view, projectionMatrix=projection, renderer=bullet.ER_TINY_RENDERER)
    Image.fromarray(np.asarray(rgba, dtype=np.uint8).reshape((FRAME_HEIGHT, FRAME_WIDTH, 4))[:, :, :3], mode="RGB").save(frame_path, format="JPEG", quality=88)


def run_articulated_simulation(
    workspace: Path,
    *,
    morphology: str,
    duration_s: float,
    mode: str,
    scenario: str,
    run_id: str | None,
    artifact_revision: str | None,
    on_state: Callable[[dict[str, Any], dict[str, Any]], None] | None,
    allow_declared_morphology: bool = False,
) -> dict[str, Any]:
    """Generic position-control adapter for arm, hand, mobile-manipulator and legged URDFs."""
    supported = {"robotic_hand", "robotic_arm_hand", "articulated_arm", "mobile_manipulator", "quadruped"}
    if morphology not in supported and not allow_declared_morphology:
        raise ValueError(f"no simulator adapter is installed for morphology '{morphology}'")
    urdfs = [workspace / "robot.urdf", *sorted((workspace / "model").glob("*.urdf"))]
    urdf_path = next((path for path in urdfs if path.is_file()), None)
    if urdf_path is None:
        raise FileNotFoundError("articulated adapter requires a project URDF in model/ or robot.urdf")
    actual_run_id = run_id or f"run_{uuid.uuid4().hex[:12]}"
    run_dir, frames_dir = workspace / "runs" / actual_run_id, workspace / "runs" / actual_run_id / "frames"
    if run_dir.exists():
        raise FileExistsError(f"run already exists: {actual_run_id}")
    frames_dir.mkdir(parents=True)
    bullet, pybullet_data = _require_pybullet()
    client_id = bullet.connect(bullet.DIRECT)
    signals: list[dict[str, Any]] = []
    states: list[dict[str, Any]] = []
    frames: list[dict[str, Any]] = []
    stderr, status, controller_log = "", "task_failed", io.StringIO()
    started = time.monotonic()
    try:
        bullet.resetSimulation(physicsClientId=client_id)
        bullet.setAdditionalSearchPath(pybullet_data.getDataPath(), physicsClientId=client_id)
        # This adapter validates commanded joint motion; it is deliberately
        # kinematic until a morphology-specific dynamics/contact model is added.
        bullet.setGravity(0, 0, 0, physicsClientId=client_id)
        bullet.setTimeStep(SIM_DT, physicsClientId=client_id)
        bullet.loadURDF("plane.urdf", physicsClientId=client_id)
        robot_id = bullet.loadURDF(str(urdf_path), [0, 0, 0.04], useFixedBase=True, physicsClientId=client_id)
        joint_indices = {bullet.getJointInfo(robot_id, index, physicsClientId=client_id)[1].decode("utf-8"): index for index in range(bullet.getNumJoints(robot_id, physicsClientId=client_id))}
        movable = [name for name, index in joint_indices.items() if bullet.getJointInfo(robot_id, index, physicsClientId=client_id)[2] != bullet.JOINT_FIXED]
        if not movable:
            raise RuntimeError("articulated adapter requires at least one movable joint")
        initial = {name: float(bullet.getJointState(robot_id, joint_indices[name], physicsClientId=client_id)[0]) for name in movable}
        controller_path = workspace / "controller.py"
        targets = _articulated_targets(controller_path, movable, initial) if controller_path.is_file() else initial
        targets = {name: max(-6.28, min(6.28, value)) for name, value in targets.items()}
        indices, values = [joint_indices[name] for name in targets], list(targets.values())
        total_steps, sample_every = max(1, int(round(duration_s / SIM_DT))), max(1, int(round((1 / SAMPLE_HZ) / SIM_DT)))
        frame_steps = {0, total_steps // 2, total_steps - 1}
        for step in range(total_steps):
            bullet.setJointMotorControlArray(robot_id, indices, bullet.POSITION_CONTROL, targetPositions=values, forces=[50.0] * len(indices), physicsClientId=client_id)
            bullet.stepSimulation(physicsClientId=client_id)
            if step % sample_every == 0 or step == total_steps - 1:
                position, quat = bullet.getBasePositionAndOrientation(robot_id, physicsClientId=client_id)
                current = {name: float(bullet.getJointState(robot_id, joint_indices[name], physicsClientId=client_id)[0]) for name in movable}
                velocity = {name: float(bullet.getJointState(robot_id, joint_indices[name], physicsClientId=client_id)[1]) for name in movable}
                error = max((abs(current[name] - targets.get(name, current[name])) for name in movable), default=0.0)
                sample = {"t": round((step + 1) * SIM_DT, 6), "base_pos": [float(v) for v in position], "base_quat": [float(v) for v in quat], "joints": current}
                signal = {"t": sample["t"], "joint_target_error_rad": error, "dist_to_target_m": error, "yaw_rad": _yaw(quat, bullet), "joint_velocity_rad_s": max((abs(v) for v in velocity.values()), default=0.0)}
                states.append(sample); signals.append(signal)
                if on_state: on_state(sample, signal)
            if step in frame_steps:
                frame_path = frames_dir / f"robot_rgb_{step:06d}.jpg"; _articulated_camera(bullet, robot_id, frame_path)
                frames.append({"camera": "robot_rgb", "t": round((step + 1) * SIM_DT, 6), "path": str(frame_path)})
            if mode == "live": time.sleep(max(0.0, started + (step + 1) * SIM_DT - time.monotonic()))
        status = "task_success" if signals and signals[-1]["joint_target_error_rad"] < 0.08 else "task_failed"
    except Exception:
        status, stderr = "crashed", traceback.format_exc(limit=12)
    finally:
        if client_id >= 0: bullet.disconnect(physicsClientId=client_id)
    summary = {"final_base_pose": {"xyz": states[-1]["base_pos"] if states else [0, 0, 0], "rpy": [0, 0, 0]}, "distance_to_target_m": signals[-1]["dist_to_target_m"] if signals else None, "collisions": 0, "max_tilt_deg": 0.0, "sim_time_s": signals[-1]["t"] if signals else 0.0}
    _write_jsonl(run_dir / "signals.jsonl", signals); _write_jsonl(run_dir / "states.jsonl", states)
    (run_dir / "controller.log").write_text(controller_log.getvalue(), encoding="utf-8")
    record = {"schema_version": "0.1.0", "run_id": actual_run_id, "artifact_revision": artifact_revision or _artifact_revision(workspace), "status": status, "stderr": stderr[:2000], "telemetry_summary": summary, "evidence": {"frames": frames, "signals_path": str(run_dir / "signals.jsonl")}, "state_samples_path": str(run_dir / "states.jsonl"), "mode": mode, "scenario": scenario, "adapter": "articulated_position_control"}
    record_path = run_dir / "run_record.json"; record_path.write_text(json.dumps(record, indent=2) + "\n", encoding="utf-8"); record["record_path"] = str(record_path)
    return record


def _rail_mission(workspace: Path) -> tuple[list[dict[str, Any]], list[str]]:
    """Read a bounded one-dimensional route from a train project mission."""
    try:
        mission = json.loads((workspace / "mission.json").read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        mission = {}
    route = mission.get("route") if isinstance(mission, Mapping) else None
    rows = [row for row in route if isinstance(row, Mapping)] if isinstance(route, list) else []
    if not rows:
        rows = [{"node": "depot", "distance_m": 0.0}, {"node": "destination", "distance_m": 20.0}]
    normalised: list[dict[str, Any]] = []
    for index, row in enumerate(rows):
        try:
            distance = max(0.0, float(row.get("distance_m", index * 10.0)))
        except (TypeError, ValueError):
            distance = index * 10.0
        normalised.append({"node": str(row.get("node") or f"node_{index}"), "distance_m": distance})
    normalised.sort(key=lambda row: float(row["distance_m"]))
    consist = mission.get("consist") if isinstance(mission, Mapping) else None
    cars = consist.get("cars") if isinstance(consist, Mapping) else None
    car_names = [str(car) for car in cars] if isinstance(cars, list) else ["C-01", "C-02", "C-03"]
    return normalised, car_names


def _rail_controller(workspace: Path, route: list[dict[str, Any]]) -> Callable[[dict[str, Any]], Mapping[str, Any]]:
    """Load a project route controller, falling back to a conservative throttle."""
    path = workspace / "train_controller.py"
    if not path.is_file():
        return lambda _: {"throttle": 0.6, "brake": 0.0}
    module_name = f"robopilot_rail_controller_{uuid.uuid4().hex}"
    spec = importlib.util.spec_from_file_location(module_name, path)
    if spec is None or spec.loader is None:
        raise RuntimeError("cannot load train_controller.py")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    direct = getattr(module, "compute_train_command", None)
    if callable(direct):
        return direct
    state_type = getattr(module, "TrainState", None)
    controller_type = getattr(module, "YardShuttleController", None)
    if callable(state_type) and callable(controller_type):
        try:
            mission = json.loads((workspace / "mission.json").read_text(encoding="utf-8"))
            controller = controller_type(mission)
        except (OSError, json.JSONDecodeError, KeyError, TypeError, ValueError):
            return lambda _: {"throttle": 0.6, "brake": 0.0}

        def command(observation: dict[str, Any]) -> Mapping[str, Any]:
            state = state_type(
                observation["track"]["node"],
                observation["odometry"]["position_m"],
                observation["odometry"]["speed_mps"],
                coupler_ok=observation["safety"]["coupler_ok"],
                brake_pressure_ok=observation["safety"]["brake_pressure_ok"],
            )
            result = controller.command(state)
            return result if isinstance(result, Mapping) else {}

        return command
    return lambda _: {"throttle": 0.6, "brake": 0.0}


def _rail_camera(bullet: Any, locomotive_id: int, frame_path: Path) -> None:
    position, _ = bullet.getBasePositionAndOrientation(locomotive_id)
    eye = [position[0] - 3.2, position[1] - 4.0, 2.5]
    target = [position[0] + 1.8, position[1], 0.35]
    view = bullet.computeViewMatrix(eye, target, [0.0, 0.0, 1.0])
    projection = bullet.computeProjectionMatrixFOV(fov=57, aspect=FRAME_WIDTH / FRAME_HEIGHT, nearVal=0.03, farVal=80.0)
    _, _, rgba, _, _ = bullet.getCameraImage(FRAME_WIDTH, FRAME_HEIGHT, viewMatrix=view, projectionMatrix=projection, renderer=bullet.ER_TINY_RENDERER)
    Image.fromarray(np.asarray(rgba, dtype=np.uint8).reshape((FRAME_HEIGHT, FRAME_WIDTH, 4))[:, :, :3], mode="RGB").save(frame_path, format="JPEG", quality=88)


def run_rail_train_simulation(
    workspace: Path,
    *,
    duration_s: float,
    mode: str,
    scenario: str,
    run_id: str | None,
    artifact_revision: str | None,
    on_state: Callable[[dict[str, Any], dict[str, Any]], None] | None,
) -> dict[str, Any]:
    """Run the bounded kinematic rail-train adapter with visual/numerical evidence.

    This adapter owns a one-dimensional, fixed-order consist. It deliberately
    does not claim wheel/rail contact, derailment, or flexible coupler physics;
    those require a later high-fidelity adapter. It does provide real PyBullet
    scene frames, train-specific commands, and a durable evidence record.
    """
    actual_run_id = run_id or f"run_{uuid.uuid4().hex[:12]}"
    run_dir, frames_dir = workspace / "runs" / actual_run_id, workspace / "runs" / actual_run_id / "frames"
    if run_dir.exists():
        raise FileExistsError(f"run already exists: {actual_run_id}")
    frames_dir.mkdir(parents=True)
    route, cars = _rail_mission(workspace)
    destination = float(route[-1]["distance_m"])
    controller = _rail_controller(workspace, route)
    bullet, pybullet_data = _require_pybullet()
    client_id = bullet.connect(bullet.DIRECT)
    signals: list[dict[str, Any]] = []
    states: list[dict[str, Any]] = []
    frames: list[dict[str, Any]] = []
    status, stderr = "task_failed", ""
    started = time.monotonic()
    try:
        bullet.resetSimulation(physicsClientId=client_id)
        bullet.setAdditionalSearchPath(pybullet_data.getDataPath(), physicsClientId=client_id)
        bullet.setGravity(0, 0, -9.81, physicsClientId=client_id)
        bullet.setTimeStep(SIM_DT, physicsClientId=client_id)
        bullet.loadURDF("plane.urdf", physicsClientId=client_id)
        track_length = max(20.0, destination + 8.0)
        rail_shape = bullet.createVisualShape(bullet.GEOM_BOX, halfExtents=[track_length / 2.0, 0.025, 0.03], rgbaColor=[0.25, 0.28, 0.32, 1.0], physicsClientId=client_id)
        for y in (-0.32, 0.32):
            bullet.createMultiBody(baseMass=0.0, baseVisualShapeIndex=rail_shape, basePosition=[track_length / 2.0, y, 0.05], physicsClientId=client_id)
        tie_shape = bullet.createVisualShape(bullet.GEOM_BOX, halfExtents=[0.12, 0.55, 0.035], rgbaColor=[0.42, 0.29, 0.18, 1.0], physicsClientId=client_id)
        for distance in np.arange(0.0, track_length + 0.1, 0.8):
            bullet.createMultiBody(baseMass=0.0, baseVisualShapeIndex=tie_shape, basePosition=[float(distance), 0.0, 0.02], physicsClientId=client_id)
        locomotive_shape = bullet.createVisualShape(bullet.GEOM_BOX, halfExtents=[0.72, 0.28, 0.22], rgbaColor=[0.18, 0.34, 0.78, 1.0], physicsClientId=client_id)
        car_shape = bullet.createVisualShape(bullet.GEOM_BOX, halfExtents=[0.62, 0.26, 0.18], rgbaColor=[0.68, 0.22, 0.16, 1.0], physicsClientId=client_id)
        locomotive_id = bullet.createMultiBody(baseMass=0.0, baseVisualShapeIndex=locomotive_shape, basePosition=[0.0, 0.0, 0.32], physicsClientId=client_id)
        car_ids = [bullet.createMultiBody(baseMass=0.0, baseVisualShapeIndex=car_shape, basePosition=[-1.5 - index * 1.35, 0.0, 0.28], physicsClientId=client_id) for index in range(len(cars))]
        total_steps, sample_every = max(1, int(round(duration_s / SIM_DT))), max(1, int(round((1 / SAMPLE_HZ) / SIM_DT)))
        frame_steps = {0, total_steps // 2, total_steps - 1}
        position_m, speed_mps, throttle, brake = 0.0, 0.0, 0.0, 0.0
        final_step = 0
        for step in range(total_steps):
            node = max((item for item in route if float(item["distance_m"]) <= position_m), key=lambda item: float(item["distance_m"]), default=route[0])
            observation = {
                "t": round(step * SIM_DT, 6),
                "odometry": {"position_m": position_m, "speed_mps": speed_mps},
                "track": {"node": node["node"], "destination_m": destination},
                "safety": {"coupler_ok": True, "brake_pressure_ok": True},
            }
            command = controller(observation)
            if not isinstance(command, Mapping):
                raise TypeError("train controller must return a command mapping")
            throttle = max(0.0, min(1.0, float(command.get("throttle", command.get("traction", 0.6)))))
            brake = max(0.0, min(1.0, float(command.get("brake", 0.0))))
            acceleration = throttle * 1.8 - brake * 3.2 - speed_mps * 0.12
            speed_mps = max(0.0, min(12.0, speed_mps + acceleration * SIM_DT))
            position_m = min(destination, position_m + speed_mps * SIM_DT)
            bullet.resetBasePositionAndOrientation(locomotive_id, [position_m, 0.0, 0.32], [0.0, 0.0, 0.0, 1.0], physicsClientId=client_id)
            for index, car_id in enumerate(car_ids):
                bullet.resetBasePositionAndOrientation(car_id, [position_m - 1.5 - index * 1.35, 0.0, 0.28], [0.0, 0.0, 0.0, 1.0], physicsClientId=client_id)
            bullet.stepSimulation(physicsClientId=client_id)
            if step % sample_every == 0 or step == total_steps - 1:
                distance = max(0.0, destination - position_m)
                sample = {"t": round((step + 1) * SIM_DT, 6), "base_pos": [position_m, 0.0, 0.32], "base_quat": [0.0, 0.0, 0.0, 1.0], "joints": {"train_speed_mps": speed_mps}}
                signal = {"t": sample["t"], "dist_to_target_m": distance, "yaw_rad": 0.0, "train_speed_mps": speed_mps, "traction": throttle, "brake": brake, "route_progress_m": position_m, "coupler_ok": 1.0}
                states.append(sample); signals.append(signal)
                if on_state: on_state(sample, signal)
            if step in frame_steps:
                frame_path = frames_dir / f"robot_rgb_{step:06d}.jpg"
                _rail_camera(bullet, locomotive_id, frame_path)
                frames.append({"camera": "robot_rgb", "t": round((step + 1) * SIM_DT, 6), "path": str(frame_path), "source": "rail_train_kinematic"})
            if position_m >= destination - 0.25 and speed_mps < 0.12:
                status = "task_success"
                final_step = step
                break
            if mode == "live": time.sleep(max(0.0, started + (step + 1) * SIM_DT - time.monotonic()))
            final_step = step
        final_t = round((final_step + 1) * SIM_DT, 6)
        if not signals or signals[-1]["t"] < final_t:
            distance = max(0.0, destination - position_m)
            states.append({"t": final_t, "base_pos": [position_m, 0.0, 0.32], "base_quat": [0.0, 0.0, 0.0, 1.0], "joints": {"train_speed_mps": speed_mps}})
            signals.append({"t": final_t, "dist_to_target_m": distance, "yaw_rad": 0.0, "train_speed_mps": speed_mps, "traction": throttle, "brake": brake, "route_progress_m": position_m, "coupler_ok": 1.0})
        if len(frames) < 2 or frames[-1]["t"] < final_t:
            frame_path = frames_dir / "robot_rgb_final.jpg"
            _rail_camera(bullet, locomotive_id, frame_path)
            frames.append({"camera": "robot_rgb", "t": final_t, "path": str(frame_path), "source": "rail_train_kinematic"})
        if signals and max(0.0, destination - position_m) <= 0.25:
            status = "task_success"
    except Exception:
        status, stderr = "crashed", traceback.format_exc(limit=12)
    finally:
        if client_id >= 0: bullet.disconnect(physicsClientId=client_id)
    summary = {"final_base_pose": {"xyz": states[-1]["base_pos"] if states else [0, 0, 0], "rpy": [0, 0, 0]}, "distance_to_target_m": signals[-1]["dist_to_target_m"] if signals else None, "collisions": 0, "max_tilt_deg": 0.0, "sim_time_s": signals[-1]["t"] if signals else 0.0, "train_speed_mps": signals[-1]["train_speed_mps"] if signals else 0.0, "route_progress_m": signals[-1]["route_progress_m"] if signals else 0.0}
    _write_jsonl(run_dir / "signals.jsonl", signals); _write_jsonl(run_dir / "states.jsonl", states)
    (run_dir / "controller.log").write_text("", encoding="utf-8")
    record = {"schema_version": "0.1.0", "run_id": actual_run_id, "artifact_revision": artifact_revision or _artifact_revision(workspace), "status": status, "stderr": stderr[:2000], "telemetry_summary": summary, "evidence": {"frames": frames, "signals_path": str(run_dir / "signals.jsonl")}, "state_samples_path": str(run_dir / "states.jsonl"), "mode": mode, "scenario": scenario, "adapter": "rail_train_kinematic"}
    record_path = run_dir / "run_record.json"; record_path.write_text(json.dumps(record, indent=2) + "\n", encoding="utf-8"); record["record_path"] = str(record_path)
    return record


# A terse name is useful to the project-tool adapter and mirrors its contract.
run_project = run_simulation


def _cli() -> int:
    parser = argparse.ArgumentParser(description="Run RoboPilot's deterministic differential-drive simulator")
    parser.add_argument("--project-dir", type=Path, default=Path("/tmp/robopilot_sim_smoke"))
    parser.add_argument("--duration-s", type=float, default=6.0)
    parser.add_argument("--mode", choices=("batch", "live"), default="batch")
    parser.add_argument("--scenario", default="default")
    parser.add_argument("--fresh", action="store_true", help="overwrite the baseline project controller")
    args = parser.parse_args()
    create_demo_project(args.project_dir, overwrite=args.fresh)
    record = run_simulation(args.project_dir, duration_s=args.duration_s, mode=args.mode, scenario=args.scenario)
    print(json.dumps(record, indent=2))
    return 0 if record["status"] == "task_success" else 1


if __name__ == "__main__":  # pragma: no cover - CLI smoke entry point
    sys.exit(_cli())
