"""Deterministic PyBullet runner for the differential-drive project adapter.

This module deliberately writes a durable run directory.  Agent-facing tools
can return its compact summary while numerical and visual evidence stays local
and can be requested by path/time later.

The generated controller ABI is intentionally small::

    def compute_wheel_commands(observation: dict) -> dict[str, float]:
        return {"left_wheel_rad_s": 8.0, "right_wheel_rad_s": 8.0}

``observation["oracle"]`` is explicitly simulator/evaluation data.  A future
ROS adapter can provide the same robot-facing fields without that key.
"""

from __future__ import annotations

import argparse
import contextlib
import hashlib
import importlib.util
import io
import json
import math
import sys
import time
import traceback
import uuid
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Callable, Mapping

import numpy as np
from PIL import Image

from .morphology import DEFAULT_SPEC, normalize_spec, write_morphology


SIM_DT = 1.0 / 240.0
SAMPLE_HZ = 20.0
FRAME_WIDTH = 320
FRAME_HEIGHT = 240
SUCCESS_DISTANCE_M = 0.30
TARGET_XY = (1.8, 0.0)

DEFAULT_CONTROLLER = '''"""Baseline rover controller generated by RoboPilot.

The target coordinates are marked oracle/evaluation because they come from the
simulator. Replace this with perception-driven logic when adding real sensors.
"""
import json
import math
from pathlib import Path


def _mission() -> dict:
    path = Path(__file__).with_name("mission.json")
    try:
        value = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return {"mode": "target_seek", "parameters": {}}
    return value if isinstance(value, dict) else {"mode": "target_seek", "parameters": {}}


def compute_wheel_commands(observation: dict) -> dict[str, float]:
    mission = _mission()
    parameters = mission.get("parameters", {})
    parameters = parameters if isinstance(parameters, dict) else {}
    mode = mission.get("mode", "target_seek")
    if mode == "wheel_velocity":
        return {
            "left_wheel_rad_s": float(parameters.get("left_wheel_rad_s", 0.0)),
            "right_wheel_rad_s": float(parameters.get("right_wheel_rad_s", 0.0)),
        }
    if mode == "circle":
        speed = float(parameters.get("speed_rad_s", 6.0))
        turn = abs(float(parameters.get("turn_rad_s", 2.0)))
        direction = -1.0 if parameters.get("direction") == "clockwise" else 1.0
        return {"left_wheel_rad_s": speed - direction * turn, "right_wheel_rad_s": speed + direction * turn}
    x, y, _ = observation["odometry"]["position_xyz"]
    yaw = observation["odometry"]["yaw_rad"]
    target_x, target_y = observation["oracle"]["target_xy"]
    heading = math.atan2(target_y - y, target_x - x)
    error = (heading - yaw + math.pi) % (2 * math.pi) - math.pi
    distance = math.hypot(target_x - x, target_y - y)
    if distance < 0.14:
        return {"left_wheel_rad_s": 0.0, "right_wheel_rad_s": 0.0}
    forward = min(float(parameters.get("max_speed_rad_s", 7.0)), 3.0 + distance * 2.0)
    turn = max(-4.5, min(4.5, float(parameters.get("turn_gain", 5.0)) * error))
    return {"left_wheel_rad_s": forward - turn, "right_wheel_rad_s": forward + turn}
'''


@dataclass(frozen=True)
class Controller:
    compute: Callable[[dict[str, Any]], Mapping[str, Any] | tuple[Any, Any] | list[Any]]
    path: Path


def create_demo_project(workspace: str | Path, *, overwrite: bool = False) -> Path:
    """Create the hand-written golden-path project and return its directory."""

    directory = Path(workspace).resolve()
    write_morphology(directory, DEFAULT_SPEC)
    controller_path = directory / "controller.py"
    if overwrite or not controller_path.exists():
        controller_path.write_text(DEFAULT_CONTROLLER, encoding="utf-8")
    return directory


def _require_pybullet() -> tuple[Any, Any]:
    try:
        import pybullet as bullet
        import pybullet_data
    except ImportError as exc:  # pragma: no cover - depends on environment setup
        raise RuntimeError("PyBullet is required: install requirements.txt") from exc
    return bullet, pybullet_data


def _load_spec(workspace: Path) -> dict[str, Any]:
    spec_path = workspace / "spec.json"
    if not spec_path.exists():
        return normalize_spec(DEFAULT_SPEC)
    try:
        raw = json.loads(spec_path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        raise ValueError(f"cannot read {spec_path.name}: {exc}") from exc
    return normalize_spec(raw)


def _artifact_revision(workspace: Path) -> str:
    digest = hashlib.sha256()
    for name in ("spec.json", "robot.urdf", "controller.py", "mission.json"):
        path = workspace / name
        digest.update(name.encode("utf-8"))
        if path.exists():
            digest.update(path.read_bytes())
    return f"rev_{digest.hexdigest()[:12]}"


def _load_controller(path: Path) -> Controller:
    if not path.exists():
        raise FileNotFoundError(f"controller not found: {path}")
    module_name = f"robopilot_controller_{uuid.uuid4().hex}"
    module_spec = importlib.util.spec_from_file_location(module_name, path)
    if module_spec is None or module_spec.loader is None:
        raise RuntimeError(f"cannot load controller: {path}")
    module = importlib.util.module_from_spec(module_spec)
    module_spec.loader.exec_module(module)
    compute = getattr(module, "compute_wheel_commands", None)
    if not callable(compute):
        raise TypeError("controller must define compute_wheel_commands(observation)")
    return Controller(compute=compute, path=path)


def _commands(result: Any) -> tuple[float, float]:
    if isinstance(result, Mapping):
        left = result.get("left_wheel_rad_s", result.get("left"))
        right = result.get("right_wheel_rad_s", result.get("right"))
    elif isinstance(result, (tuple, list)) and len(result) == 2:
        left, right = result
    else:
        raise TypeError("controller result must be wheel mapping or [left, right]")
    left, right = float(left), float(right)
    if not (math.isfinite(left) and math.isfinite(right)):
        raise ValueError("wheel commands must be finite")
    # A bad agent edit must not destabilise the physics loop indefinitely.
    return max(-40.0, min(40.0, left)), max(-40.0, min(40.0, right))


def _yaw(quaternion: list[float] | tuple[float, ...], bullet: Any) -> float:
    return float(bullet.getEulerFromQuaternion(quaternion)[2])


def _camera_frame(bullet: Any, robot_id: int, frame_path: Path) -> None:
    position, quaternion = bullet.getBasePositionAndOrientation(robot_id)
    yaw = _yaw(quaternion, bullet)
    forward = np.array([math.cos(yaw), math.sin(yaw), 0.0])
    eye = np.array(position, dtype=float) + forward * 0.14 + np.array([0.0, 0.0, 0.11])
    target = eye + forward * 3.0
    view = bullet.computeViewMatrix(eye.tolist(), target.tolist(), [0.0, 0.0, 1.0])
    projection = bullet.computeProjectionMatrixFOV(fov=72, aspect=FRAME_WIDTH / FRAME_HEIGHT, nearVal=0.03, farVal=8.0)
    _, _, rgba, _, _ = bullet.getCameraImage(
        FRAME_WIDTH,
        FRAME_HEIGHT,
        viewMatrix=view,
        projectionMatrix=projection,
        renderer=bullet.ER_TINY_RENDERER,
    )
    pixels = np.asarray(rgba, dtype=np.uint8).reshape((FRAME_HEIGHT, FRAME_WIDTH, 4))
    Image.fromarray(pixels[:, :, :3], mode="RGB").save(frame_path, format="JPEG", quality=88)


def _observation(
    sim_time_s: float,
    position: tuple[float, float, float],
    yaw_rad: float,
    wheel_positions: tuple[float, float],
    wheel_velocities: tuple[float, float],
) -> dict[str, Any]:
    return {
        "t": round(sim_time_s, 6),
        "odometry": {"position_xyz": list(position), "yaw_rad": yaw_rad, "frame_id": "world"},
        "joint_state": {
            "names": ["left_wheel_joint", "right_wheel_joint"],
            "position_rad": list(wheel_positions),
            "velocity_rad_s": list(wheel_velocities),
        },
        "oracle": {
            "source": "simulator/evaluation",
            "target_xy": list(TARGET_XY),
            "note": "Not a physical robot sensor; do not rely on this for hardware controllers.",
        },
    }


def _write_jsonl(path: Path, rows: list[dict[str, Any]]) -> None:
    with path.open("w", encoding="utf-8") as handle:
        for row in rows:
            handle.write(json.dumps(row, separators=(",", ":")) + "\n")


def run_simulation(
    workspace: str | Path,
    *,
    duration_s: float = 10.0,
    mode: str = "batch",
    scenario: str = "default",
    run_id: str | None = None,
    artifact_revision: str | None = None,
    on_state: Callable[[dict[str, Any], dict[str, Any]], None] | None = None,
) -> dict[str, Any]:
    """Run a project controller and write a canonical, session-local run record.

    ``mode="live"`` uses identical deterministic physics but throttles each step
    to real time. Streaming is intentionally owned by the platform layer; it
    can replay the returned ``state_samples_path`` for batch runs or relay
    samples while this callable is executed on a worker for live runs.
    """

    if not 0.1 <= float(duration_s) <= 120.0:
        raise ValueError("duration_s must be in [0.1, 120]")
    if mode not in {"batch", "live"}:
        raise ValueError("mode must be 'batch' or 'live'")
    if not scenario or len(scenario) > 80:
        raise ValueError("scenario must be a non-empty string up to 80 characters")

    workspace_path = Path(workspace).resolve()
    workspace_path.mkdir(parents=True, exist_ok=True)
    spec = _load_spec(workspace_path)
    urdf_path = workspace_path / "robot.urdf"
    if not urdf_path.exists():
        write_morphology(workspace_path, spec)
    controller_path = workspace_path / "controller.py"
    if not controller_path.exists():
        controller_path.write_text(DEFAULT_CONTROLLER, encoding="utf-8")

    actual_run_id = run_id or f"run_{uuid.uuid4().hex[:12]}"
    if not actual_run_id.replace("_", "").replace("-", "").isalnum():
        raise ValueError("run_id may contain only letters, digits, '_' and '-'")
    run_dir = workspace_path / "runs" / actual_run_id
    if run_dir.exists():
        raise FileExistsError(f"run already exists: {actual_run_id}")
    frames_dir = run_dir / "frames"
    frames_dir.mkdir(parents=True)

    revision = artifact_revision or _artifact_revision(workspace_path)
    signals: list[dict[str, Any]] = []
    states: list[dict[str, Any]] = []
    frames: list[dict[str, Any]] = []
    controller_output = io.StringIO()
    stderr = ""
    status = "task_failed"
    bullet, pybullet_data = _require_pybullet()
    client_id = bullet.connect(bullet.DIRECT)
    started = time.monotonic()

    try:
        bullet.resetSimulation(physicsClientId=client_id)
        bullet.setAdditionalSearchPath(pybullet_data.getDataPath(), physicsClientId=client_id)
        bullet.setGravity(0, 0, -9.81, physicsClientId=client_id)
        bullet.setTimeStep(SIM_DT, physicsClientId=client_id)
        bullet.loadURDF("plane.urdf", physicsClientId=client_id)

        morphology = spec["morphology"]
        initial_z = morphology["wheel_radius_m"] + morphology["body_height_m"] / 2.0 + 0.002
        robot_id = bullet.loadURDF(
            str(urdf_path), [0.0, 0.0, initial_z], useFixedBase=False, flags=bullet.URDF_USE_INERTIA_FROM_FILE,
            physicsClientId=client_id,
        )
        bullet.changeDynamics(robot_id, -1, lateralFriction=0.9, physicsClientId=client_id)
        for joint_index in range(bullet.getNumJoints(robot_id, physicsClientId=client_id)):
            bullet.changeDynamics(robot_id, joint_index, lateralFriction=1.4, physicsClientId=client_id)

        target_id = bullet.createMultiBody(
            baseMass=0.0,
            baseVisualShapeIndex=bullet.createVisualShape(
                bullet.GEOM_SPHERE, radius=0.10, rgbaColor=[0.92, 0.05, 0.04, 1.0], physicsClientId=client_id
            ),
            basePosition=[TARGET_XY[0], TARGET_XY[1], 0.10],
            physicsClientId=client_id,
        )
        bullet.setCollisionFilterGroupMask(target_id, -1, 0, 0, physicsClientId=client_id)

        joint_indices = {
            bullet.getJointInfo(robot_id, index, physicsClientId=client_id)[1].decode("utf-8"): index
            for index in range(bullet.getNumJoints(robot_id, physicsClientId=client_id))
        }
        try:
            left_joint = joint_indices["left_wheel_joint"]
            right_joint = joint_indices["right_wheel_joint"]
        except KeyError as exc:
            raise RuntimeError("URDF must expose left_wheel_joint and right_wheel_joint") from exc
        bullet.setJointMotorControlArray(
            robot_id, [left_joint, right_joint], bullet.VELOCITY_CONTROL, targetVelocities=[0, 0], forces=[2.5, 2.5],
            physicsClientId=client_id,
        )
        controller = _load_controller(controller_path)

        total_steps = max(1, int(round(float(duration_s) / SIM_DT)))
        sample_every = max(1, int(round((1.0 / SAMPLE_HZ) / SIM_DT)))
        frame_steps = {0, total_steps // 2, total_steps - 1}
        yaw_initial: float | None = None
        last_commands = (0.0, 0.0)

        for step in range(total_steps):
            sim_time_s = step * SIM_DT
            position_raw, quat_raw = bullet.getBasePositionAndOrientation(robot_id, physicsClientId=client_id)
            joint_states = bullet.getJointStates(robot_id, [left_joint, right_joint], physicsClientId=client_id)
            wheel_positions = (float(joint_states[0][0]), float(joint_states[1][0]))
            wheel_velocities = (float(joint_states[0][1]), float(joint_states[1][1]))
            yaw_rad = _yaw(quat_raw, bullet)
            if yaw_initial is None:
                yaw_initial = yaw_rad
            observation = _observation(sim_time_s, tuple(position_raw), yaw_rad, wheel_positions, wheel_velocities)
            try:
                with contextlib.redirect_stdout(controller_output):
                    last_commands = _commands(controller.compute(observation))
            except Exception:
                status = "crashed"
                stderr = traceback.format_exc(limit=8)
                break
            bullet.setJointMotorControlArray(
                robot_id,
                [left_joint, right_joint],
                bullet.VELOCITY_CONTROL,
                targetVelocities=list(last_commands),
                forces=[2.5, 2.5],
                physicsClientId=client_id,
            )
            bullet.stepSimulation(physicsClientId=client_id)

            if step % sample_every == 0 or step == total_steps - 1:
                position_raw, quat_raw = bullet.getBasePositionAndOrientation(robot_id, physicsClientId=client_id)
                joint_states = bullet.getJointStates(robot_id, [left_joint, right_joint], physicsClientId=client_id)
                yaw_rad = _yaw(quat_raw, bullet)
                distance = math.hypot(position_raw[0] - TARGET_XY[0], position_raw[1] - TARGET_XY[1])
                roll, pitch, _ = bullet.getEulerFromQuaternion(quat_raw)
                sample = {
                    "t": round((step + 1) * SIM_DT, 6),
                    "base_pos": [float(value) for value in position_raw],
                    "base_quat": [float(value) for value in quat_raw],
                    "joints": {"left_wheel": float(joint_states[0][0]), "right_wheel": float(joint_states[1][0])},
                }
                signal = {
                    "t": sample["t"],
                    "base_x_m": sample["base_pos"][0],
                    "base_y_m": sample["base_pos"][1],
                    "yaw_rad": yaw_rad,
                    "dist_to_target_m": distance,
                    "left_command_rad_s": last_commands[0],
                    "right_command_rad_s": last_commands[1],
                    "left_wheel_velocity_rad_s": float(joint_states[0][1]),
                    "right_wheel_velocity_rad_s": float(joint_states[1][1]),
                    "roll_rad": float(roll),
                    "pitch_rad": float(pitch),
                }
                states.append(sample)
                signals.append(signal)
                if on_state is not None:
                    on_state(sample, signal)
            if step in frame_steps:
                frame_path = frames_dir / f"robot_rgb_{step:06d}.jpg"
                _camera_frame(bullet, robot_id, frame_path)
                frames.append({"camera": "robot_rgb", "t": round((step + 1) * SIM_DT, 6), "path": str(frame_path)})
            if mode == "live":
                target_wall = started + (step + 1) * SIM_DT
                time.sleep(max(0.0, target_wall - time.monotonic()))

        if not signals:
            raise RuntimeError("simulation did not produce any state samples")
        final = signals[-1]
        final_state = states[-1]
        if status != "crashed":
            status = "task_success" if final["dist_to_target_m"] < SUCCESS_DISTANCE_M else "task_failed"
        yaw_start = signals[0]["yaw_rad"]
        yaw_end = final["yaw_rad"]
        # Keep yaw drift intuitive across +/- pi.
        yaw_drift = math.degrees((yaw_end - yaw_start + math.pi) % (2 * math.pi) - math.pi)
        max_tilt = max(math.degrees(max(abs(row["roll_rad"]), abs(row["pitch_rad"]))) for row in signals)
        collisions = 0  # Ground contacts and target proximity are not task collisions.
        summary = {
            "final_base_pose": {
                "xyz": final_state["base_pos"],
                "rpy": [final["roll_rad"], final["pitch_rad"], final["yaw_rad"]],
            },
            "distance_to_target_m": final["dist_to_target_m"],
            "total_yaw_drift_deg": yaw_drift,
            "mean_wheel_velocities": {
                "left": float(np.mean([row["left_wheel_velocity_rad_s"] for row in signals])),
                "right": float(np.mean([row["right_wheel_velocity_rad_s"] for row in signals])),
            },
            "collisions": collisions,
            "max_tilt_deg": max_tilt,
            "sim_time_s": final["t"],
        }
    except Exception:
        if not stderr:
            status = "crashed"
            stderr = traceback.format_exc(limit=12)
        summary = {
            "final_base_pose": {"xyz": [0.0, 0.0, 0.0], "rpy": [0.0, 0.0, 0.0]},
            "distance_to_target_m": None,
            "total_yaw_drift_deg": 0.0,
            "mean_wheel_velocities": {"left": 0.0, "right": 0.0},
            "collisions": 0,
            "max_tilt_deg": 0.0,
            "sim_time_s": 0.0,
        }
    finally:
        if client_id >= 0:
            bullet.disconnect(physicsClientId=client_id)

    stderr = stderr[:2000]
    controller_log_path = run_dir / "controller.log"
    controller_log_path.write_text(controller_output.getvalue()[-10_000:], encoding="utf-8")
    signals_path = run_dir / "signals.jsonl"
    states_path = run_dir / "states.jsonl"
    _write_jsonl(signals_path, signals)
    _write_jsonl(states_path, states)
    record = {
        "schema_version": "0.1.0",
        "run_id": actual_run_id,
        "artifact_revision": revision,
        "status": status,
        "stderr": stderr,
        "telemetry_summary": summary,
        "evidence": {"frames": frames, "signals_path": str(signals_path)},
        "state_samples_path": str(states_path),
        "controller_log_path": str(controller_log_path),
        "mode": mode,
        "scenario": scenario,
        "oracle": {"target_xy": list(TARGET_XY), "source": "simulator/evaluation"},
    }
    record_path = run_dir / "run_record.json"
    record_path.write_text(json.dumps(record, indent=2) + "\n", encoding="utf-8")
    record["record_path"] = str(record_path)
    return record


# A terse name is useful to the project-tool adapter and mirrors its contract.
run_project = run_simulation


def _cli() -> int:
    parser = argparse.ArgumentParser(description="Run RoboPilot's deterministic differential-drive simulator")
    parser.add_argument("--project-dir", type=Path, default=Path("/tmp/robopilot_sim_smoke"))
    parser.add_argument("--duration-s", type=float, default=6.0)
    parser.add_argument("--mode", choices=("batch", "live"), default="batch")
    parser.add_argument("--scenario", default="default")
    parser.add_argument("--fresh", action="store_true", help="overwrite the baseline project controller")
    args = parser.parse_args()
    create_demo_project(args.project_dir, overwrite=args.fresh)
    record = run_simulation(args.project_dir, duration_s=args.duration_s, mode=args.mode, scenario=args.scenario)
    print(json.dumps(record, indent=2))
    return 0 if record["status"] == "task_success" else 1


if __name__ == "__main__":  # pragma: no cover - CLI smoke entry point
    sys.exit(_cli())
