(() => {
  "use strict";
  const $ = (selector) => document.querySelector(selector);
  const elements = {
    conversation: $("#conversation"), activity: $("#activity"), stageRow: $("#stageRow"), runStatus: $("#runStatus"), runLabel: $("#runLabel"), viewportNote: $("#viewportNote"),
    sim: $("#simCanvas"), camera: $("#cameraCanvas"), chart: $("#telemetryCanvas"), timeline: $("#timeline"), timeReadout: $("#timeReadout"), play: $("#playButton"),
    frameMeta: $("#frameMeta"), metric: $("#metricValue"), telemetryTime: $("#telemetryTime"), evidence: $("#runEvidence"),
    fileTree: $("#fileTree"), fileExplorer: $("#fileExplorer"), editor: $("#codeEditor"), filePath: $("#filePath"), lineHint: $("#lineHint"), editStatus: $("#editStatus"), diff: $("#diffView"),
    revision: $("#revisionBadge"), fileRevision: $("#fileRevision"), chatInput: $("#chatInput"), run: $("#runButton"), stop: $("#stopButton"), mode: $("#modeToggle"), toast: $("#toast"),
    project: $("#projectSelect"), chatSession: $("#chatSessionSelect"), model: $("#modelSelect"), fileTreeToggle: $("#toggleFileTree"), workspace: $("#workspacePanel"), workspaceToggle: $("#toggleWorkspace"), agentWorking: $("#agentWorking"), agentWorkingText: $("#agentWorkingText"), recordedRuns: $("#recordedRunSelect"), stageNote: $("#stageNote")
  };
  const stageNames = ["spec", "morphology", "build", "observe", "heal", "export"];
  const state = {
    projectId: "rover-demo", chatSessionId: null, chatSessions: [], projectPreview: { title: "Rover", morphology: "differential_drive", can_run: true }, model: "gpt-5.6-luna:medium", runId: null, revision: "rev_17", stages: {}, states: [], telemetry: [], playing: false, playIndex: 0, live: false, mockControl: null, cameraImage: null, recordedRuns: [], renderEpoch: 0, reconnectTimer: null, reconnectAttempts: 0, interruptedTurn: false,
    files: {
      "spec.json": '{\n  "morphology": "diff_drive_rover",\n  "camera": true,\n  "task": "drive to red ball"\n}',
      "robot.urdf": '<robot name="red_ball_rover">\n  <link name="base_link"/>\n  <joint name="left_wheel_joint" type="continuous"/>\n  <joint name="right_wheel_joint" type="continuous"/>\n</robot>',
      "controller.py": 'TARGET = (2.1, 0.0)\n\ndef drive_to_target(robot):\n    distance, bearing = robot.target_observation()\n    left = 8.0 - bearing * 1.4\n    right = 8.0 + bearing * 1.4\n    robot.set_wheel_velocity("left_wheel", left)\n    robot.set_wheel_velocity("right_wheel", right)\n    return distance < 0.3\n',
      "ros2_ws/rover_controller.py": 'def main():\n    # Generated ROS 2 controller export\n    pass\n'
    }, selectedFile: "controller.py", previousText: "", lastAgentLines: null
  };
  function setStatus(text, kind) { elements.runStatus.className = `run-status ${kind || ""}`; elements.runStatus.lastElementChild.textContent = text; elements.run.disabled = kind === "running"; elements.stop.disabled = kind !== "running"; }
  function setAgentWorking(active, text) { elements.agentWorking.classList.toggle("working", active); elements.agentWorking.classList.toggle("done", !active); if (text) elements.agentWorkingText.textContent = text; }
  function toast(text) { elements.toast.textContent = text; elements.toast.classList.add("show"); clearTimeout(toast.timer); toast.timer = setTimeout(() => elements.toast.classList.remove("show"), 2700); }
  function renderStages() { elements.stageRow.innerHTML = stageNames.map((name) => `<span class="stage-chip ${state.stages[name] || ""}">${name}</span>`).join(""); }
  function addMessage(role, text) { const item = document.createElement("article"); item.className = `message ${role}`; item.innerHTML = `<span class="message-role">${role === "user" ? "You" : "RoboPilot"}</span><p></p>`; item.querySelector("p").textContent = text; elements.conversation.append(item); elements.conversation.scrollTop = elements.conversation.scrollHeight; }
  function addActivity(event) { const item = document.createElement("li"); item.className = event.role || "progress"; if (event.file) { const button = document.createElement("button"); button.textContent = event.summary; button.onclick = () => selectFile(event.file, event.lines); item.append(button); } else item.textContent = event.summary; elements.activity.append(item); elements.activity.parentElement.scrollTop = elements.activity.parentElement.scrollHeight; }
  function canvasSize(canvas) { const rect = canvas.getBoundingClientRect(), ratio = window.devicePixelRatio || 1; const w = Math.max(1, Math.floor(rect.width * ratio)), h = Math.max(1, Math.floor(rect.height * ratio)); if (canvas.width !== w || canvas.height !== h) { canvas.width = w; canvas.height = h; } return { ctx: canvas.getContext("2d"), w, h, ratio }; }
  function currentSample() { return state.states[Math.min(state.playIndex, Math.max(0, state.states.length - 1))] || { t: 0, base_pos: [0, 0, 0], base_quat: [0, 0, 0, 1], joints: {} }; }
  function renderSim() { const { ctx, w, h } = canvasSize(elements.sim); ctx.clearRect(0, 0, w, h); ctx.fillStyle = "#eef2f1"; ctx.fillRect(0, 0, w, h); const scale = Math.min(w / 6.4, h / 4.5); const origin = [w / 2, h / 2 + 8]; ctx.strokeStyle = "#d9e2e1"; ctx.lineWidth = 1; for (let x = -3; x <= 3; x++) { ctx.beginPath(); ctx.moveTo(origin[0] + x * scale, 0); ctx.lineTo(origin[0] + x * scale, h); ctx.stroke(); } for (let y = -2; y <= 2; y++) { ctx.beginPath(); ctx.moveTo(0, origin[1] - y * scale); ctx.lineTo(w, origin[1] - y * scale); ctx.stroke(); }
    if (!state.projectPreview.can_run) { ctx.fillStyle = "#6d7c91"; ctx.fillRect(w / 2 - 38, h / 2 - 23, 76, 46); ctx.strokeStyle = "#334155"; ctx.lineWidth = 4; for (let x = -24; x <= 24; x += 12) { ctx.beginPath(); ctx.moveTo(w / 2 + x, h / 2 - 23); ctx.lineTo(w / 2 + x, h / 2 - 58); ctx.stroke(); } ctx.fillStyle = "#475569"; ctx.font = "12px sans-serif"; ctx.textAlign = "center"; ctx.fillText(state.projectPreview.title || "Project preview", w / 2, h / 2 + 73); ctx.fillText(`${state.projectPreview.morphology || "unknown"} · adapter required`, w / 2, h / 2 + 91); ctx.textAlign = "start"; return; }
    const target = [origin[0] + 2.1 * scale, origin[1]]; ctx.fillStyle = "#dc4c45"; ctx.beginPath(); ctx.arc(...target, 12, 0, Math.PI * 2); ctx.fill(); ctx.fillStyle = "#fff"; ctx.beginPath(); ctx.arc(target[0] - 3, target[1] - 4, 3, 0, Math.PI * 2); ctx.fill();
    const sample = currentSample(); if (!sample) return; const pos = [origin[0] + sample.base_pos[0] * scale, origin[1] - sample.base_pos[1] * scale]; ctx.save(); ctx.translate(...pos); ctx.rotate(-.055); ctx.fillStyle = "#2f69c9"; ctx.fillRect(-16, -12, 32, 24); ctx.fillStyle = "#19263a"; ctx.fillRect(-13, -16, 8, 32); ctx.fillRect(5, -16, 8, 32); ctx.fillStyle = "#8dc3ed"; ctx.fillRect(5, -6, 8, 12); ctx.strokeStyle = "rgba(37,99,235,.22)"; ctx.lineWidth = 2; ctx.beginPath(); ctx.moveTo(14, 0); ctx.lineTo(55, 0); ctx.stroke(); ctx.restore();
    ctx.fillStyle = "#687588"; ctx.font = `${Math.max(10, w / 48)}px ui-monospace`; ctx.fillText("x", w - 18, origin[1] - 4); ctx.fillText("y", origin[0] + 5, 14); }
  function renderCamera() { const { ctx, w, h } = canvasSize(elements.camera); const recorded = state.cameraImage; if (recorded && recorded.complete && recorded.naturalWidth) { ctx.fillStyle = "#0f172a"; ctx.fillRect(0, 0, w, h); const scale = Math.min(w / recorded.naturalWidth, h / recorded.naturalHeight), drawW = recorded.naturalWidth * scale, drawH = recorded.naturalHeight * scale; ctx.drawImage(recorded, (w - drawW) / 2, (h - drawH) / 2, drawW, drawH); return; } ctx.fillStyle = "#b9d4df"; ctx.fillRect(0, 0, w, h * .5); ctx.fillStyle = "#d6d6c5"; ctx.fillRect(0, h * .5, w, h * .5); const sample = currentSample(); if (!sample) { ctx.fillStyle = "#64748b"; ctx.font = "12px sans-serif"; ctx.fillText("Recorded camera frame available after a simulation run", 12, 24); return; } const dist = Math.max(.18, 2.1 - sample.base_pos[0]); const ball = Math.max(9, Math.min(h * .26, 17 / dist)); const bx = w / 2 + Math.sin(sample.t * .5) * w * .045, by = h * .53; ctx.fillStyle = "#d9423b"; ctx.beginPath(); ctx.arc(bx, by, ball, 0, Math.PI * 2); ctx.fill(); ctx.strokeStyle = "rgba(255,255,255,.75)"; ctx.strokeRect(bx - ball - 5, by - ball - 5, ball * 2 + 10, ball * 2 + 10); ctx.fillStyle = "#fff"; ctx.font = "10px ui-monospace"; ctx.fillText("preview pending recorded frame", 8, 15); }
  function loadCameraFrame(event) { if (!event.url) return; const epoch = state.renderEpoch, projectId = state.projectId, runId = event.run_id; const image = new Image(); image.onload = () => { if (epoch !== state.renderEpoch || projectId !== state.projectId || (state.runId && runId !== state.runId)) return; state.cameraImage = image; elements.frameMeta.textContent = `robot_rgb · t = ${Number(event.t || 0).toFixed(2)} s · recorded frame`; renderCamera(); }; image.onerror = () => { if (epoch === state.renderEpoch) addActivity({ role: "progress", summary: "A recorded camera frame could not be loaded." }); }; image.src = event.url; }
  function renderChart() { const { ctx, w, h } = canvasSize(elements.chart); ctx.fillStyle = "#f8fafc"; ctx.fillRect(0, 0, w, h); if (!state.telemetry.length) return; const pad = { l: 30, r: 9, t: 12, b: 20 }, maxT = Math.max(10, state.telemetry[state.telemetry.length - 1].t), maxD = 5; ctx.strokeStyle = "#e3e8ef"; ctx.lineWidth = 1; for (let i = 0; i < 4; i++) { const y = pad.t + i * (h - pad.t - pad.b) / 3; ctx.beginPath(); ctx.moveTo(pad.l, y); ctx.lineTo(w - pad.r, y); ctx.stroke(); } ctx.strokeStyle = "#2563eb"; ctx.lineWidth = 2; ctx.beginPath(); state.telemetry.forEach((point, i) => { const x = pad.l + point.t / maxT * (w - pad.l - pad.r); const y = pad.t + (1 - Math.min(maxD, point.dist_to_target) / maxD) * (h - pad.t - pad.b); i ? ctx.lineTo(x, y) : ctx.moveTo(x, y); }); ctx.stroke(); ctx.fillStyle = "#718096"; ctx.font = "9px ui-monospace"; ctx.fillText("5m", 4, pad.t + 4); ctx.fillText("0m", 4, h - pad.b + 3); ctx.fillText("0s", pad.l, h - 5); ctx.fillText(`${maxT.toFixed(0)}s`, w - 22, h - 5); }
  function updateReplay() { const sample = currentSample(); elements.timeline.max = String(Math.max(0, state.states.length - 1)); elements.timeline.value = String(state.playIndex); elements.timeReadout.textContent = `t = ${sample.t.toFixed(2)} s`; elements.frameMeta.textContent = state.states.length ? `robot_rgb · t = ${sample.t.toFixed(2)} s · selected evidence` : "Current project preview · initial pose"; const visibleMetric = state.telemetry[Math.min(state.playIndex, state.telemetry.length - 1)]; if (visibleMetric) { elements.metric.textContent = `${visibleMetric.dist_to_target.toFixed(2)} m`; elements.telemetryTime.textContent = `t = ${visibleMetric.t.toFixed(1)} s`; } renderSim(); renderCamera(); renderChart(); }
  function selectFile(file, lines) { if (!Object.hasOwn(state.files, file)) return; state.selectedFile = file; state.lastAgentLines = lines || null; elements.fileTree.querySelectorAll("button[data-file]").forEach((tab) => tab.classList.toggle("active", tab.dataset.file === file)); elements.filePath.textContent = file; elements.editor.value = state.files[file]; elements.lineHint.textContent = lines ? `agent touched lines ${lines[0]}–${lines[1]}` : "editable"; if (lines) { const rows = elements.editor.value.split("\n"), start = rows.slice(0, Math.max(0, lines[0] - 1)).join("\n").length + (lines[0] > 1 ? 1 : 0), end = rows.slice(0, lines[1]).join("\n").length; elements.editor.focus(); elements.editor.setSelectionRange(start, end); } }
  function buildFileTree(files) { const root = {}; files.forEach((file) => { let branch = root; file.split("/").forEach((part, index, parts) => { if (index === parts.length - 1) branch[part] = file; else branch = branch[part] || (branch[part] = {}); }); }); return root; }
  function appendTree(branch, container) { Object.keys(branch).sort().forEach((name) => { const value = branch[name]; if (typeof value === "string") { const button = document.createElement("button"); button.className = `file-tree-file ${value === state.selectedFile ? "active" : ""}`; button.dataset.file = value; button.textContent = name; button.onclick = () => selectFile(value); container.append(button); return; } const details = document.createElement("details"); details.open = true; const summary = document.createElement("summary"); summary.textContent = name; details.append(summary); const nested = document.createElement("div"); nested.className = "file-tree-branch"; appendTree(value, nested); details.append(nested); container.append(details); }); }
  function renderFiles() { const files = Object.keys(state.files).sort(); if (!files.length) { elements.fileTree.textContent = "No editable project files."; elements.editor.value = ""; return; } if (!Object.hasOwn(state.files, state.selectedFile)) state.selectedFile = files[0]; elements.fileTree.replaceChildren(); appendTree(buildFileTree(files), elements.fileTree); selectFile(state.selectedFile); }
  function setRevision(revision) { state.revision = revision; elements.revision.textContent = revision; elements.fileRevision.textContent = revision; }
  function renderDiff(before, after) { const oldLines = before.split("\n"), newLines = after.split("\n"); let out = ""; const max = Math.max(oldLines.length, newLines.length); for (let i = 0; i < max; i++) { if (oldLines[i] !== newLines[i]) { if (oldLines[i] !== undefined) out += `<span class="del">− ${escapeHtml(oldLines[i])}</span>\n`; if (newLines[i] !== undefined) out += `<span class="add">+ ${escapeHtml(newLines[i])}</span>\n`; } } elements.diff.innerHTML = out || "No textual change."; }
  function escapeHtml(text) { return String(text).replace(/[&<>]/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;" })[c]); }
  function renderProjects(projects) { const known = Array.from(new Set([...(projects || []), state.projectId])).sort(); elements.project.replaceChildren(...known.map((project) => { const option = document.createElement("option"); option.value = project; option.textContent = project; option.selected = project === state.projectId; return option; })); }
  function renderChatSessions(sessions) { state.chatSessions = Array.isArray(sessions) ? sessions : []; elements.chatSession.replaceChildren(...state.chatSessions.map((session) => { const option = document.createElement("option"); option.value = session.session_id; option.textContent = session.title || "New conversation"; option.selected = session.session_id === state.chatSessionId; return option; })); elements.chatSession.disabled = !state.chatSessions.length; }
  function renderRecordedRuns() { const selected = state.runId || elements.recordedRuns.value; elements.recordedRuns.replaceChildren(); const placeholder = document.createElement("option"); placeholder.value = ""; placeholder.textContent = state.recordedRuns.length ? "Select recorded run…" : "No recorded runs"; elements.recordedRuns.append(placeholder); state.recordedRuns.forEach((run) => { const option = document.createElement("option"); option.value = run.run_id; option.textContent = `${run.run_id} · ${run.status} · ${run.mode}`; option.selected = run.run_id === selected; elements.recordedRuns.append(option); }); elements.recordedRuns.disabled = !state.recordedRuns.length; }
  function processEvent(event) { if (!event || !event.type) return; if (event.project_id && event.project_id !== state.projectId && event.type !== "project_selected") return; if (event.type === "project_selected") { state.projectId = event.project_id; state.chatSessionId = event.chat_session_id || null; state.model = event.model || state.model; elements.model.value = state.model; renderProjects(event.projects); renderChatSessions(event.chat_sessions); state.files = {}; state.selectedFile = ""; state.recordedRuns = []; renderRecordedRuns(); resetRun(); elements.stageNote.textContent = "Waiting for Codex activity."; setAgentWorking(false, state.interruptedTurn ? "Codex was interrupted by a service restart. Continue to resume it." : "Codex is idle."); elements.conversation.replaceChildren(); elements.activity.replaceChildren(); (Array.isArray(event.chat_history) ? event.chat_history : []).forEach((message) => addMessage(message.role, message.text)); if (!event.chat_history?.length) addMessage("assistant", "New conversation. Tell me what you want to build."); if (event.created) toast(`Created ${state.projectId}`); return; } if (event.type === "stage") { if (event.status === "reset") state.stages = {}; else state.stages[event.stage] = event.status === "start" ? "active" : event.status === "done" ? "done" : "error"; if (event.note) elements.stageNote.textContent = event.note; renderStages(); if (event.note && event.status === "start") addActivity({ role: "progress", summary: event.note }); }
    if (event.type === "project_preview") { state.projectPreview = event; elements.run.disabled = !event.can_run; elements.viewportNote.textContent = event.can_run ? "Current project preview" : event.message; elements.runLabel.textContent = event.title || state.projectId; updateReplay(); }
    if (event.type === "run_unsupported") { setStatus("Simulator adapter required", "error"); addActivity({ role: "progress", summary: event.message }); toast(event.message); }
    if (event.type === "chat") addMessage(event.role || "assistant", event.text);
    if (event.type === "turn_started") { state.interruptedTurn = false; setAgentWorking(true, "Codex is working…"); addActivity({ role: "progress", summary: "Codex accepted this request and is working." }); }
    if (event.type === "turn_completed") { state.interruptedTurn = false; setAgentWorking(false, "Codex is done."); addActivity({ role: "tool_result", summary: "Codex completed this turn." }); }
    if (event.type === "turn_error" || event.type === "runner_error" || event.type === "turn_stopped") { state.interruptedTurn = false; setAgentWorking(false, event.message ? "Codex stopped with an error." : "Codex is stopped."); addActivity({ role: "progress", summary: event.message || "Codex stopped before completing this turn." }); toast(event.message || "Codex stopped."); }
    if (event.type === "agent_step") { addActivity(event); if (event.file) selectFile(event.file, event.lines); }
    if (event.type === "sim_state") { state.runId = event.run_id || state.runId; state.states.push(event); if (!state.playing) state.playIndex = state.states.length - 1; elements.runLabel.textContent = `${state.runId || "run"} · ${state.live ? "live" : "replay"}`; elements.viewportNote.textContent = state.live ? "Live simulation stream" : "Recorded simulation replay"; updateReplay(); }
    if (event.type === "telemetry") { state.telemetry.push({ t: event.t, ...(event.series || {}) }); updateReplay(); }
    if (event.type === "sim_frame") { loadCameraFrame(event); updateReplay(); }
    if (event.type === "recorded_runs") { state.recordedRuns = Array.isArray(event.runs) ? event.runs : []; renderRecordedRuns(); }
    if (event.type === "run_loaded") { resetRun(); state.runId = event.run_id; state.live = false; setStatus("Recorded run loaded", ""); }
    if (event.type === "files") { if (event.contents && typeof event.contents === "object") { if (Array.isArray(event.tree)) state.files = {}; Object.entries(event.contents).forEach(([path, content]) => { if (typeof content === "string") state.files[path] = content; }); renderFiles(); } if (event.changed && event.changed[0]) selectFile(event.changed[0]); if (event.artifact_revision) setRevision(event.artifact_revision); }
    if (event.type === "run_summary") { setStatus(event.status === "task_success" ? "Task succeeded" : event.status || "Completed", event.status === "task_success" ? "success" : ""); const t = event.telemetry_summary || {}; elements.evidence.innerHTML = `<div><dt>Run</dt><dd>${event.run_id || "—"}</dd></div><div><dt>Artifact</dt><dd>${event.artifact_revision || state.revision}</dd></div><div><dt>Collisions</dt><dd>${t.collisions ?? "—"}</dd></div>`; if (event.artifact_revision) setRevision(event.artifact_revision); }
  }
  function resetRun() { state.renderEpoch += 1; state.states = []; state.telemetry = []; state.playIndex = 0; state.stages = {}; state.runId = null; state.playing = false; state.cameraImage = null; elements.play.textContent = "▶"; elements.viewportNote.textContent = "Current project preview"; renderStages(); updateReplay(); }
  function sendToServer(payload) { if (state.socket && state.socket.readyState === WebSocket.OPEN) { state.socket.send(JSON.stringify({ ...payload, project_id: payload.project_id || state.projectId, chat_session_id: payload.chat_session_id || state.chatSessionId, model: payload.model || state.model })); return true; } return false; }
  function scheduleReconnect() { if (state.reconnectTimer || !window.location.host || window.location.protocol === "file:") return; const delay = Math.min(5000, 500 * 2 ** Math.min(state.reconnectAttempts, 4)); state.reconnectAttempts += 1; state.reconnectTimer = setTimeout(() => { state.reconnectTimer = null; initSocket(); }, delay); }
  function initSocket() { if (!window.location.host || window.location.protocol === "file:" || state.socket) return; try { const url = `${location.protocol === "https:" ? "wss" : "ws"}://${location.host}/ws`; const socket = new WebSocket(url); state.socket = socket; socket.onopen = () => { state.reconnectAttempts = 0; setStatus("Ready", ""); setAgentWorking(false, state.interruptedTurn ? "Codex was interrupted by a service restart. Continue to resume it." : "Codex is idle."); sendToServer({ type: "select_project", project_id: state.projectId }); toast("Connected to RoboPilot service"); }; socket.onmessage = (message) => { try { processEvent(JSON.parse(message.data)); } catch (_) {} }; socket.onerror = () => socket.close(); socket.onclose = () => { if (state.socket === socket) { const working = elements.agentWorking.classList.contains("working"); state.socket = null; state.interruptedTurn = state.interruptedTurn || working; setAgentWorking(false, working ? "Codex was interrupted by a service restart. Reconnecting…" : "RoboPilot service disconnected. Reconnecting…"); setStatus("Service reconnecting", "error"); scheduleReconnect(); } }; } catch (_) { state.socket = null; setAgentWorking(false, "RoboPilot service is unavailable. Reconnecting…"); setStatus("Service unavailable", "error"); scheduleReconnect(); } }
  function initInteractions() { $("#chatForm").onsubmit = (event) => { event.preventDefault(); const text = elements.chatInput.value.trim(); if (!text) return; elements.chatInput.value = ""; if (!sendToServer({ type: "user_message", text })) { addMessage("user", text); addActivity({ role: "progress", summary: "Message was not sent: the RoboPilot service is disconnected." }); toast("Start the RoboPilot server, then send again."); } };
    elements.chatInput.onkeydown = (event) => { if ((event.metaKey || event.ctrlKey) && event.key === "Enter") $("#chatForm").requestSubmit(); };
    elements.project.onchange = () => sendToServer({ type: "select_project", project_id: elements.project.value });
    elements.chatSession.onchange = () => sendToServer({ type: "select_chat_session", chat_session_id: elements.chatSession.value });
    $("#newChatSessionButton").onclick = () => sendToServer({ type: "new_chat_session" });
    $("#newProjectButton").onclick = () => { const raw = window.prompt("New project name (lowercase letters, numbers, hyphens)"); if (raw === null) return; const project = raw.trim().toLowerCase().replace(/[^a-z0-9-]+/g, "-").replace(/^-+|-+$/g, ""); if (!/^[a-z][a-z0-9-]{1,62}$/.test(project)) return toast("Use 2–63 lowercase characters, starting with a letter."); sendToServer({ type: "new_project", project_id: project }); };
    elements.model.onchange = () => { state.model = elements.model.value; localStorage.setItem("robopilot-codex-model", state.model); toast("Model will apply to the next Codex turn."); };
    elements.fileTreeToggle.onclick = () => { const collapsed = elements.fileExplorer.classList.toggle("collapsed"); elements.fileTreeToggle.textContent = collapsed ? "Expand" : "Collapse"; elements.fileTreeToggle.setAttribute("aria-expanded", String(!collapsed)); };
    elements.workspaceToggle.onclick = () => { const collapsed = elements.workspace.classList.toggle("collapsed"); document.querySelector(".workbench").classList.toggle("workspace-collapsed", collapsed); elements.workspaceToggle.textContent = collapsed ? "‹" : "›"; elements.workspaceToggle.title = collapsed ? "Expand workspace" : "Collapse workspace"; elements.workspaceToggle.setAttribute("aria-label", elements.workspaceToggle.title); elements.workspaceToggle.setAttribute("aria-expanded", String(!collapsed)); };
    elements.recordedRuns.onchange = () => { const runId = elements.recordedRuns.value; if (runId) sendToServer({ type: "load_run", run_id: runId }); };
    elements.run.onclick = () => { resetRun(); state.live = elements.mode.checked; if (!sendToServer({ type: "run_project", mode: state.live ? "live" : "batch" })) { setStatus("Service disconnected", "error"); toast("Simulation was not started: RoboPilot service is disconnected."); } else setStatus("Running", "running"); };
    elements.stop.onclick = () => { if (state.mockControl) state.mockControl.stop(); sendToServer({ type: "stop_run" }); setStatus("Stopped", ""); addActivity({ role: "progress", summary: "Simulation stopped; recorded evidence remains available." }); };
    $("#continueButton").onclick = () => { if (!sendToServer({ type: "continue_autonomously" })) toast("Continuation was not sent: RoboPilot service is disconnected."); };
    $("#compareButton").onclick = () => { toast(state.runId ? "Comparison is ready when a second run is recorded." : "Run the project first to collect evidence."); };
    elements.mode.onchange = () => { const spans = elements.mode.parentElement.querySelectorAll("span"); spans[0].style.color = elements.mode.checked ? "" : "#2563eb"; spans[1].style.color = elements.mode.checked ? "#2563eb" : ""; };
    elements.timeline.oninput = () => { state.playIndex = Number(elements.timeline.value); state.playing = false; elements.play.textContent = "▶"; updateReplay(); };
    elements.play.onclick = () => { if (!state.states.length) return; state.playing = !state.playing; elements.play.textContent = state.playing ? "Ⅱ" : "▶"; };
    $("#resetViewButton").onclick = () => { state.playIndex = 0; state.playing = false; elements.play.textContent = "▶"; updateReplay(); };
    $("#saveFileButton").onclick = () => { const before = state.files[state.selectedFile], after = elements.editor.value; if (before === after) return toast("No file changes to save."); state.files[state.selectedFile] = after; const next = `rev_${Number((state.revision.match(/\d+/) || [17])[0]) + 1}`; setRevision(next); renderDiff(before, after); elements.editStatus.textContent = `Saved as ${next}; visible to Codex.`; addActivity({ role: "edit", summary: `You edited ${state.selectedFile}`, file: state.selectedFile }); sendToServer({ type: "save_file", path: state.selectedFile, content: after }); toast("Saved a new workspace revision."); };
  }
  function tick() { if (state.playing && state.states.length) { state.playIndex = (state.playIndex + 1) % state.states.length; updateReplay(); } requestAnimationFrame(tick); }
  function init() { const savedModel = localStorage.getItem("robopilot-codex-model"); if (savedModel && Array.from(elements.model.options).some((option) => option.value === savedModel)) state.model = savedModel; elements.model.value = state.model; renderProjects([state.projectId]); renderStages(); renderFiles(); addMessage("assistant", "Tell me what you want to build. I’ll keep the project workspace, evidence, and run history in this thread."); setStatus("Ready", ""); updateReplay(); initInteractions(); initSocket(); window.addEventListener("resize", updateReplay); requestAnimationFrame(tick); }
  window.RoboPilot = { processEvent, state }; init();
})();
